- nama: Menyiapkan lingkungan Node.js
  penggunaan: tindakan/setup-node@v4.1.0
  dengan:
    # Tetapkan selalu-auth di npmrc.
    selalu-auth: # opsional, defaultnya salah
    # Spesifikasi Versi Versi yang akan digunakan. Contoh: 12.x, 10.15.1, >=10.15.0.
    versi-simpul: # opsional
    # File yang berisi versi Spesifikasi versi yang akan digunakan. Contoh: package.json, .nvmrc, .node-version, .tool-versions.
    node-version-file: # opsional
    # Arsitektur target yang akan digunakan Node. Contoh: x86, x64. Akan menggunakan arsitektur sistem secara default.
    arsitektur: # opsional
    # Tetapkan opsi ini jika Anda ingin tindakan memeriksa versi terbaru yang tersedia dan memenuhi spesifikasi versi.
    check-latest: # opsional
    # Registri opsional untuk menyiapkan autentikasi. Akan menyetel registri dalam file .npmrc dan .yarnrc tingkat proyek, dan menyiapkan autentikasi untuk membaca dari env.NODE_AUTH_TOKEN.
    registry-url: # opsional
    # Cakupan opsional untuk autentikasi terhadap registri yang memiliki cakupan. Akan kembali ke pemilik repositori saat menggunakan registri Paket GitHub (https://npm.pkg.github.com/).
    cakupan: # opsional
    # Digunakan untuk menarik distribusi node dari node-versions. Karena ada nilai default, nilai ini biasanya tidak disediakan oleh pengguna. Saat menjalankan tindakan ini di github.com, nilai default sudah cukup. Saat menjalankan di GHES, Anda dapat meneruskan token akses pribadi untuk github.com jika Anda mengalami pembatasan kecepatan.
    token: # opsional, defaultnya adalah ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Digunakan untuk menentukan pengelola paket untuk penyimpanan sementara di direktori default. Nilai yang didukung: npm, yarn, pnpm.
    cache: # opsional
    # Digunakan untuk menentukan jalur ke berkas dependensi: package-lock.json, yarn.lock, dll. Mendukung karakter pengganti atau daftar nama berkas untuk menyimpan beberapa dependensi dalam cache.
    jalur-ketergantungan-cache: # opsional
